// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetSupportedFormats():Promise<Array<string>>;

export function Greet(arg1:string):Promise<string>;

export function ProcessImage(arg1:string,arg2:main.ProcessOptions):Promise<string>;

export function ProcessImageFromBase64(arg1:string,arg2:main.ProcessOptions):Promise<string>;
