// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetSupportedFormats() {
  return window['go']['main']['App']['GetSupportedFormats']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ProcessImage(arg1, arg2) {
  return window['go']['main']['App']['ProcessImage'](arg1, arg2);
}

export function ProcessImageFromBase64(arg1, arg2) {
  return window['go']['main']['App']['ProcessImageFromBase64'](arg1, arg2);
}
